ci(test): Add python build and testing
Signed-off-by: AlexNg <contact@ngjx.org>

diff --git a/.github/workflows/test-worker.yml b/.github/workflows/test-worker.yml
--- a/.github/workflows/test-worker.yml
+++ b/.github/workflows/test-worker.yml
@@ -54,11 +54,68 @@ jobs:
           set -xe
           make test/go
 
+  python-build:
+    name: Building python
+    runs-on: ubuntu-latest
+
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v4
+
+      - name: Set up Python 3.x
+        uses: actions/setup-python@v5
+        with:
+          python-version: 3.x
+
+      - name: Install dependencies
+        run: |
+          set -xe
+          make install/python
+
+      - name: Build
+        run: |
+          set -xe
+          make build/python
+
+  python-test:
+    name: "Test python ${{ matrix.python-version }} on ${{ matrix.os }}"
+    runs-on: "${{ matrix.os }}-latest"
+
+    continue-on-error: ${{ startsWith(matrix.python-version, '~') }} # Allows unstable Python versions to fail
+
+    strategy:
+      fail-fast: false
+      matrix:
+        os:
+          - ubuntu
+          - windows
+          - macos
+        python-version: ["3.9", "3.10", "3.11", "3.12", "3.x"]
+
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v4
+
+      - name: Set up Python ${{ matrix.python-version }}
+        uses: actions/setup-python@v5
+        with:
+          python-version: ${{ matrix.python-version }}
+
+      - name: Install dependencies
+        run: |
+          set -xe
+          make install/python
+
+      - name: Test with pytest
+        run: |
+          set -xe
+          make test/python
+
   check:
     if: always()
     name: Tests Successful
     runs-on: ubuntu-latest
-    needs: [golang-test, golang-build]
+    needs: [golang-test, golang-build, python-test, python-build]
 
     steps:
       - name: Whether the whole test suite passed
